export const patientList = [
  {
    id: 1,
    name: "Michael Fernando",
    age: 45,
    gender: "Male",
    email: "michael@example.com",
    phone: "0712345678",
    address: "Colombo, Sri Lanka",
    symptoms: ["Chest Pain", "Shortness of Breath"],
    diagnosis: "Angina",
    prescribedMedication: ["Aspirin", "Nitroglycerin"],
    appointmentDate: "2025-08-10",
    doctorId: 1, 
    medicalHistory: "Diabetes, High Blood Pressure"
  },
  {
    id: 2,
    name: "Anjali Perera",
    age: 32,
    gender: "Female",
    email: "anjali@example.com",
    phone: "0776543210",
    address: "Galle, Sri Lanka",
    symptoms: ["Rash", "Itching"],
    diagnosis: "Eczema",
    prescribedMedication: ["Hydrocortisone Cream"],
    appointmentDate: "2025-08-12",
    doctorId: 2, 
    medicalHistory: "Asthma"
  }
,
  {
    id: 3,
    name: "Tharindu Silva",
    age: 28,
    gender: "Male",
    email: "tharindu@example.com",
    phone: "0709876543",
    address: "Kandy, Sri Lanka",
    symptoms: ["Headache", "Nausea"],
    diagnosis: "Migraine",
    prescribedMedication: ["Sumatriptan"],
    appointmentDate: "2025-08-13",
    doctorId: 1,
    medicalHistory: "None"
  },
  {
    id: 4,
    name: "Nadeesha Wijesinghe",
    age: 54,
    gender: "Female",
    email: "nadeesha@example.com",
    phone: "0711122233",
    address: "Matara, Sri Lanka",
    symptoms: ["Joint Pain", "Swelling"],
    diagnosis: "Arthritis",
    prescribedMedication: ["Ibuprofen", "Methotrexate"],
    appointmentDate: "2025-08-15",
    doctorId: 1,
    medicalHistory: "Hypertension"
  },
];
